/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppLinksRouteImport } from './routes/_authenticated.app.links'
import { Route as AuthenticatedAppDesignRouteImport } from './routes/_authenticated.app.design'
import { Route as AuthenticatedAppApiKeysRouteImport } from './routes/_authenticated.app.api-keys'
import { Route as ApiPublicV1ProfileRouteImport } from './routes/api/public/v1/profile'
import { Route as ApiPublicV1LinksRouteImport } from './routes/api/public/v1/links'
import { Route as ApiPublicV1LinksReorderRouteImport } from './routes/api/public/v1/links.reorder'
import { Route as ApiPublicV1LinksIdRouteImport } from './routes/api/public/v1/links.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLinksRoute = AuthenticatedAppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDesignRoute = AuthenticatedAppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppApiKeysRoute = AuthenticatedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicV1ProfileRoute = ApiPublicV1ProfileRouteImport.update({
  id: '/api/public/v1/profile',
  path: '/api/public/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LinksRoute = ApiPublicV1LinksRouteImport.update({
  id: '/api/public/v1/links',
  path: '/api/public/v1/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LinksReorderRoute = ApiPublicV1LinksReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiPublicV1LinksRoute,
} as any)
const ApiPublicV1LinksIdRoute = ApiPublicV1LinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1LinksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/r/$id': typeof RIdRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/design': typeof AuthenticatedAppDesignRoute
  '/app/links': typeof AuthenticatedAppLinksRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/v1/links': typeof ApiPublicV1LinksRouteWithChildren
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/links/$id': typeof ApiPublicV1LinksIdRoute
  '/api/public/v1/links/reorder': typeof ApiPublicV1LinksReorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/r/$id': typeof RIdRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/design': typeof AuthenticatedAppDesignRoute
  '/app/links': typeof AuthenticatedAppLinksRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/v1/links': typeof ApiPublicV1LinksRouteWithChildren
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/links/$id': typeof ApiPublicV1LinksIdRoute
  '/api/public/v1/links/reorder': typeof ApiPublicV1LinksReorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/r/$id': typeof RIdRoute
  '/_authenticated/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/_authenticated/app/design': typeof AuthenticatedAppDesignRoute
  '/_authenticated/app/links': typeof AuthenticatedAppLinksRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/v1/links': typeof ApiPublicV1LinksRouteWithChildren
  '/api/public/v1/profile': typeof ApiPublicV1ProfileRoute
  '/api/public/v1/links/$id': typeof ApiPublicV1LinksIdRoute
  '/api/public/v1/links/reorder': typeof ApiPublicV1LinksReorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/r/$id'
    | '/app/api-keys'
    | '/app/design'
    | '/app/links'
    | '/app/'
    | '/api/public/v1/links'
    | '/api/public/v1/profile'
    | '/api/public/v1/links/$id'
    | '/api/public/v1/links/reorder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/r/$id'
    | '/app/api-keys'
    | '/app/design'
    | '/app/links'
    | '/app'
    | '/api/public/v1/links'
    | '/api/public/v1/profile'
    | '/api/public/v1/links/$id'
    | '/api/public/v1/links/reorder'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/r/$id'
    | '/_authenticated/app/api-keys'
    | '/_authenticated/app/design'
    | '/_authenticated/app/links'
    | '/_authenticated/app/'
    | '/api/public/v1/links'
    | '/api/public/v1/profile'
    | '/api/public/v1/links/$id'
    | '/api/public/v1/links/reorder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  RIdRoute: typeof RIdRoute
  ApiPublicV1LinksRoute: typeof ApiPublicV1LinksRouteWithChildren
  ApiPublicV1ProfileRoute: typeof ApiPublicV1ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/links': {
      id: '/_authenticated/app/links'
      path: '/links'
      fullPath: '/app/links'
      preLoaderRoute: typeof AuthenticatedAppLinksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/design': {
      id: '/_authenticated/app/design'
      path: '/design'
      fullPath: '/app/design'
      preLoaderRoute: typeof AuthenticatedAppDesignRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/api-keys': {
      id: '/_authenticated/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AuthenticatedAppApiKeysRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/v1/profile': {
      id: '/api/public/v1/profile'
      path: '/api/public/v1/profile'
      fullPath: '/api/public/v1/profile'
      preLoaderRoute: typeof ApiPublicV1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/links': {
      id: '/api/public/v1/links'
      path: '/api/public/v1/links'
      fullPath: '/api/public/v1/links'
      preLoaderRoute: typeof ApiPublicV1LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/links/reorder': {
      id: '/api/public/v1/links/reorder'
      path: '/reorder'
      fullPath: '/api/public/v1/links/reorder'
      preLoaderRoute: typeof ApiPublicV1LinksReorderRouteImport
      parentRoute: typeof ApiPublicV1LinksRoute
    }
    '/api/public/v1/links/$id': {
      id: '/api/public/v1/links/$id'
      path: '/$id'
      fullPath: '/api/public/v1/links/$id'
      preLoaderRoute: typeof ApiPublicV1LinksIdRouteImport
      parentRoute: typeof ApiPublicV1LinksRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppApiKeysRoute: typeof AuthenticatedAppApiKeysRoute
  AuthenticatedAppDesignRoute: typeof AuthenticatedAppDesignRoute
  AuthenticatedAppLinksRoute: typeof AuthenticatedAppLinksRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppApiKeysRoute: AuthenticatedAppApiKeysRoute,
  AuthenticatedAppDesignRoute: AuthenticatedAppDesignRoute,
  AuthenticatedAppLinksRoute: AuthenticatedAppLinksRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1LinksRouteChildren {
  ApiPublicV1LinksIdRoute: typeof ApiPublicV1LinksIdRoute
  ApiPublicV1LinksReorderRoute: typeof ApiPublicV1LinksReorderRoute
}

const ApiPublicV1LinksRouteChildren: ApiPublicV1LinksRouteChildren = {
  ApiPublicV1LinksIdRoute: ApiPublicV1LinksIdRoute,
  ApiPublicV1LinksReorderRoute: ApiPublicV1LinksReorderRoute,
}

const ApiPublicV1LinksRouteWithChildren =
  ApiPublicV1LinksRoute._addFileChildren(ApiPublicV1LinksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  RIdRoute: RIdRoute,
  ApiPublicV1LinksRoute: ApiPublicV1LinksRouteWithChildren,
  ApiPublicV1ProfileRoute: ApiPublicV1ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
